
version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - zappa update --disable_progress
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 0 ]; then zappa rollback -n 1; exit 1; fi
