
version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - zappa update --disable_progres
