# Generated by Django 3.1.7 on 2021-03-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuers', '0002_auto_20210323_1840'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='from_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issuers.issueremail'),
        ),
    ]
