# Generated by Django 3.1.7 on 2021-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210323_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='slug',
            field=models.CharField(default='un-comunicado-muy-importante', max_length=255),
            preserve_default=False,
        ),
    ]
