# Generated by Django 3.1.7 on 2021-03-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210327_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
