# Generated by Django 3.1.7 on 2021-03-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuers', '0002_auto_20210323_1840'),
        ('docs', '0006_auto_20210327_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issuers.issuer'),
        ),
    ]
