# Generated by Django 3.1.7 on 2021-04-02 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20210327_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='issuer_name',
        ),
        migrations.AlterField(
            model_name='doc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
