# Generated by Django 3.1.7 on 2021-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20210402_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
