# Generated by Django 3.1.13 on 2021-08-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20210402_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ('-issued_at',)},
        ),
        migrations.AlterField(
            model_name='doc',
            name='body_md',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='from_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
