# Generated by Django 3.1.7 on 2021-09-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_auto_20210827_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='body_md',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doc',
            name='body_plain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='short_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
