# Generated by Django 3.1.7 on 2021-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
