# Generated by Django 3.1.7 on 2021-08-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuers', '0002_auto_20210323_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='avatar',
            field=models.CharField(default='🏢', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuer',
            name='color',
            field=models.CharField(default='006EFF', max_length=6),
        ),
    ]
