# Generated by Django 3.1.13 on 2021-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuers', '0003_auto_20210829_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('waiting', 'Esperando primer '), ('active', 'Activo'), ('inactive', 'Inactivto')], default='new', max_length=255),
            preserve_default=False,
        ),
    ]
